### PR TITLE
Adding Elixir Plataform.

### PR DESCRIPTION
**Pull request by CristianOliveiraDaRosa**
Hey guys.
I added Elixir plataform.
 - Added Dockerfile, Install and Deploy scripts
 - Added an example
 - Added to tests in tests/platforms.bash

Fell free to review!

### CODE REVIEW

**Comment by fsouza** [comment]
Hi @CristianOliveiraDaRosa, thanks for contributing. I tested it locally and got the following deploy output:

```
% tsuru app-deploy . -a chico
Uploading files....... ok
/home/application/current /
Could not find Hex, which is needed to build dependency :cowboy
Shall I install Hex? [Yn] ** (Mix) Could not find an SCM for dependency :cowboy from App.Mixfile
/

---- Building application image ----
 ---> Sending image to repository (0.00MB)
please wait...
please wait...
 ---> Cleaning up

---- Starting 1 new unit [web: 1] ----
 ---> Started unit f31442172c [web]

---- Binding and checking 1 new unit ----
 ---> Bound and checked unit f31442172c [web]

---- Adding routes to new units ----
 ---> Added route to unit f31442172c [web]

OK
```

Along with that, the app is not running, here are the logs:

```
% suru app-log -a chico
2015-10-29 02:22:47 +0000 [tsuru][api]: ---- Adding routes to new units ----
2015-10-29 02:22:48 +0000 [tsuru][api]:  ---> Added route to unit f31442172c [web]
2015-10-29 02:22:51 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:22:52 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:22:53 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:22:55 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:22:59 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:23:06 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:23:19 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
2015-10-29 02:23:45 +0000 [web][f31442172cdb]: ** (Mix) You're trying to run :app on Elixir v1.1.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1
```

So, two questions:

- is there a ppa for latest Elixir packages? (the answer is probably yes, there's always a ppa for that haha)
- is there a flag or parameter in mix to make it non-interactive? (I hope so)

I will have a closer look tomorrow, after some sleep :)

**Comment by CristianOliveiraDaRosa** [comment]
Hey @fsouza 
 - Actually, the default ubuntu PPA has already the lastest [Elixir version (v1.1.0)](http://elixir-lang.org/blog/2015/09/28/elixir-v1-1-0-released/). My bad, I've declared the v1.1.1 as dependecy I will change.
 - There are no way to run it silently, cause isn't a lib dependecy... it asks you to install hex locally (Hex is the "pipy of Elixir"). We can install it before, like I did with rebar.

I will change it.

**Comment by fsouza** [comment]
@CristianOliveiraDaRosa thanks for the fixes, I will test it again.

**Comment by CristianOliveiraDaRosa** [comment]
Thanks @fsouza.
With last change the script runs with no stops.

**Comment by CristianOliveiraDaRosa** [comment]
Hey @fsouza 
I've created a test app on heroku with the last changes. see here: https://aqueous-ravine-9581.herokuapp.com

I think now is everything ok :)

**Comment by fsouza** [comment]
Cool, it worked!

Thanks for contributing.

**Pull request merged**
