### PR TITLE
Adds io.js platform

### PR DESCRIPTION
**Pull request by robsonpeixoto**
It's a copy from https://github.com/iojs/docker-iojs/blob/master/1.6/Dockerfile

### CODE REVIEW

**Comment by fsouza** [comment]
@robsonpeixoto can you add an example to the ``examples`` directory? Thank you!

**Comment by robsonpeixoto** [comment]
@fsouza done in d00f3d31917d24e8e2d7a4ad8888bc93bfc10fb1

**Comment by fsouza** [comment]
Thank you!

**Comment by robsonpeixoto** [comment]
Thanks @fsouza

**Comment by robsonpeixoto** [comment]
@andrewsmedina Where is my tsuru t-shirt? =D

**Comment by andrewsmedina** [comment]
You t-shirt is here: img_20150416_162212931

**Pull request merged**
