### PR TITLE
Adding CORS

### PR DESCRIPTION
**Pull request by jonaskac**
I've added CORS to the static basebuilder with this definition (http://enable-cors.org/server_nginx.html).
The reason is since we use this to create CDNs, and our apps can't get the information from the server if CORS isn't set.

Don't know if anyone else has this problem, but seems like something that should be there.

### CODE REVIEW

**Comment by jonaskac** [comment]
Hey guys, do you think that this is something valid to add?

**Comment by fsouza** [comment]
Hi @jonaskac, thanks for bumping it and sorry for the late response. I don't think that we should enforce CORS on all applications. Maybe we could make this configurable. For example: if the environment variable ENABLE_CORS is defined, then use a config file with CORS enabled. What do you think?

And if users want to have more granular configuration on CORS settings, they can always override the config file.

Does that make sense?

**Comment by jonaskac** [comment]
Sounds like a plan, it's quite a chunk of code, what do you reckon should be editable?
Just ENABLE_CORS=true and then add all of it, or should it be more granularity to it?

**Comment by fsouza** [comment]
I think so, it's all related to CORS anyway.

We may have two versions of the file in the repository, and just move it around when the variable is defined.

**Comment by jonaskac** [comment]
Would that be something like:

1. Add a new nginx.conf called nginx_cors.conf in etc

2. Change install to:
```
#!/bin/bash -e

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install
apt-get install gcc make curl libpcre3-dev zlib1g-dev nginx -y
rm -rf /var/log/nginx /var/lib/nginx
mkdir -p /var/log/nginx /var/lib/nginx
chown -R ubuntu:ubuntu /var/lib/nginx /var/log/nginx
cp ${SOURCE_DIR}/static/Procfile ${SOURCE_DIR}/utils/Procfile

if [ $ENABLE_CORS -eq true ]; then
	cp ${SOURCE_DIR}/static/etc/nginx.conf /etc/nginx/nginx.conf
else
	cp ${SOURCE_DIR}/static/etc/nginx_cors.conf /etc/nginx/nginx.conf
fi

echo "sudo chmod 777 /dev/stdout" >> /etc/profile
```

**Comment by fsouza** [comment]
It's more complicated than that: you need to run it in the deploy script (``/var/lib/tsuru/deploy``), and the deploy script no longer runs with application environment variables, so you need to add another line before the if condition, then you can use ``-n`` to check whether the variable has some value (so users can use whatever they want).

Here is how the script would look like (you need sudo because it doesn't run as root):

```bash
#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
APP_DIR=/home/application/current

ENABLE_CORS=$(test -f /tmp/app_envs && source /tmp/app_envs && echo $ENABLE_CORS)

if [ -n "${ENABLE_CORS}" ]; then
	sudo cp ${SOURCE_DIR}/static/etc/nginx.conf /etc/nginx/nginx.conf
else
	sudo cp ${SOURCE_DIR}/static/etc/nginx_cors.conf /etc/nginx/nginx.conf
fi

set +e
test -e ${APP_DIR}/nginx.conf && sudo cp ${APP_DIR}/nginx.conf /etc/nginx/nginx.conf
set -e
```

Thank you!

**Pull request closed without merging**
